import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import "./App.css";

const API_URL = import.meta.env.VITE_API_URL || "http://127.0.0.1:8000";

const THEMES = {
  default: { accent: "#2e7d32", soft: "#e8f5e9", warm: "#fff4cf", logo: "/milgi-logo.png" },
  woman: { accent: "#c2185b", soft: "#fde4ef", warm: "#fdeaf2", logo: "/milgi-logo-2.png" },
  man: { accent: "#1565c0", soft: "#e4f1ff", warm: "#eaf4ff", logo: "/milgi-logo-3.png" },
  kids: { accent: "#ef6c00", soft: "#fff0e2", warm: "#fff3e7", logo: "/milgi-logo-4.png" },
  senior: { accent: "#4d6b57", soft: "#edf5ef", warm: "#f6f8f6", logo: "/milgi-logo.png" },
  occasional: { accent: "#d99b00", soft: "#fff6d9", warm: "#fff9e6", logo: "/milgi-logo.png" },
};

const COPY = {
  en: {
    back: "Back", home: "Home", trips: "Trips", active: "Active", profile: "Profile",
    welcome: "Welcome to MILGI", move: "Move with MILGI", preview: "Preview MILGI", previewSub: "Explore the app without an account", tagline: "Local mobility, connected.",
    chooseLanguage: "Choose your language", languageSub: "You can change this later.",
    english: "English", hindi: "हिन्दी",
    category: "Which experience is right for you?", categorySub: "Choose the experience that feels right for you.",
    woman: "Woman", man: "Man", kids: "Kids", senior: "Senior",
    use: "How will you use MILGI?", useSub: "Choose how you usually travel.",
    everyday: "Everyday travel", village: "Village mode", occasional: "Occasional use",
    everydayDesc: "Simple experience for regular journeys.", villageDesc: "Visual, simple and voice-friendly.", occasionalDesc: "A lighter experience for sometimes travel.",
    signIn: "Please Sign in to MILGI", signUp: "Create your MILGI account", signInSub: "Use your account to continue.", signUpSub: "Start your journey with MILGI.",
    fullName: "Full name", mobile: "Mobile number", email: "Email", password: "Password", create: "Create account", signInBtn: "Sign in",
    newUser: "New to MILGI? Sign up", existing: "Already have an account? Sign in", wait: "Please wait…",
    homeTitle: "Where are you going?", morning: "Good morning.", chooseService: "Please choose your service",
    setDestination: "Set destination", setDestinationDesc: "Search a place, address or landmark.",
    people: "People", peopleDesc: "Book a ride for yourself or others.",
    goods: "Goods", goodsDesc: "Local goods transport.", coming: "Coming soon",
    routes: "Regular routes", routesDesc: "Create recurring travel.", institutions: "Institutions", institutionsDesc: "Connect school, university, company or hospital transport.",
    traveller: "Who is travelling?", travellerSub: "Tell MILGI who the ride is for.", myself: "Myself", someone: "Someone else", group: "Family / group",
    destination: "Choose destination", destinationSub: "Add pickup and destination.", pickup: "Pickup", current: "Use current location", destinationLabel: "Destination", searchDestination: "Search destination", continue: "Continue",
    ride: "Choose your ride", rideSub: "Pick the option that fits you.", auto: "Auto", van: "Van", bus: "Bus", confirmRide: "Confirm ride", fare: "Estimated fare",
    searching: "Finding your partner", searchingSub: "Looking for an available MILGI partner nearby.", found: "Partner found", arriving: "Partner is arriving", arrived: "Partner has arrived", boarding: "Ready to board", secured: "Ride secured", live: "Your ride is on the way", arrivedDest: "You have arrived", payment: "Payment", rating: "How was your ride?",
    next: "Next", viewLive: "View live ride", pay: "Pay & finish", done: "Done",
    routesTitle: "Regular routes", routesSub: "Save the journeys you repeat.", createRoute: "Create a route", myRoutes: "My routes", subscription: "Subscription", routeFrom: "From", routeTo: "To", days: "Travel days", morningEvening: "Morning / Evening", plan: "Plan", saveRoute: "Save route",
    institution: "Institution transport", institutionSub: "Connect and manage existing transport.", school: "School", university: "University", company: "Company", hospital: "Hospital", institutionName: "Institution name", fleet: "Fleet", fleetSub: "Existing vehicles connected to this institution.", busFleet: "Bus fleet", vanFleet: "Van / car fleet", routeSchedule: "Route & schedule", connect: "Connect transport",
    goodsTitle: "Goods transport", goodsSub: "Local goods movement will live here.", goodsPickup: "Pickup location", goodsDelivery: "Delivery location", vehicleType: "Vehicle type", goodsNotice: "Goods booking is not available at this time.",
    tripsTitle: "Your trips", tripsSub: "Past and active journeys.", activeTitle: "Active ride", activeSub: "Your current MILGI trip.", noTrips: "No trips yet.",
    profileTitle: "Profile", profileSub: "Your MILGI account.", personal: "Personal details", preferences: "Preferences", payments: "Payments", helpSafety: "Help & safety", logout: "Log out",
    notifications: "Notifications", rideUpdate: "Ride update", routeUpdate: "Route update", account: "Account", sos: "Safety & SOS", emergency: "Emergency SOS", emergencyContact: "Emergency contact", support: "MILGI support", help: "Help centre", faqs: "FAQs", contact: "Contact support", safety: "Safety information", personalized: "Personalized experience",
  },
  hi: {
    back: "वापस", home: "होम", trips: "यात्राएँ", active: "सक्रिय", profile: "प्रोफ़ाइल",
    welcome: "MILGI में आपका स्वागत है", move: "MILGI के साथ चलें", preview: "MILGI देखें", previewSub: "बिना खाते के ऐप देखें", tagline: "आपकी स्थानीय यात्रा, अब जुड़ी हुई।",
    chooseLanguage: "अपनी भाषा चुनें", languageSub: "आप इसे बाद में बदल सकते हैं।", english: "English", hindi: "हिन्दी",
    category: "आपके लिए कौन-सा अनुभव सही है?", categorySub: "अपने लिए सही अनुभव चुनें।", woman: "महिला", man: "पुरुष", kids: "बच्चे", senior: "वरिष्ठ",
    use: "आप MILGI का उपयोग कैसे करेंगे?", useSub: "आप आमतौर पर कैसे यात्रा करते हैं, चुनें।", everyday: "रोज़ की यात्रा", village: "गाँव मोड", occasional: "कभी-कभी यात्रा", everydayDesc: "रोज़ की यात्रा के लिए सरल अनुभव।", villageDesc: "आसान, विज़ुअल और आवाज़ से मदद।", occasionalDesc: "कभी-कभी यात्रा के लिए हल्का अनुभव।",
    signIn: "MILGI में साइन इन करें", signUp: "अपना MILGI खाता बनाएँ", signInSub: "जारी रखने के लिए अपने खाते का उपयोग करें।", signUpSub: "MILGI के साथ अपनी यात्रा शुरू करें।", fullName: "पूरा नाम", mobile: "मोबाइल नंबर", email: "ईमेल", password: "पासवर्ड", create: "खाता बनाएँ", signInBtn: "साइन इन", newUser: "नए हैं? साइन अप करें", existing: "पहले से खाता है? साइन इन करें", wait: "कृपया प्रतीक्षा करें…",
    homeTitle: "आप कहाँ जा रहे हैं?", morning: "सुप्रभात।", chooseService: "कृपया अपनी सेवा चुनें", setDestination: "गंतव्य तय करें", setDestinationDesc: "जगह, पता या लैंडमार्क खोजें।", people: "लोग", peopleDesc: "अपने या किसी और के लिए राइड बुक करें।", goods: "सामान", goodsDesc: "स्थानीय सामान परिवहन।", coming: "जल्द उपलब्ध होगा", routes: "नियमित रूट", routesDesc: "बार-बार होने वाली यात्रा बनाएँ।", institutions: "संस्थान", institutionsDesc: "स्कूल, यूनिवर्सिटी, कंपनी या अस्पताल का परिवहन जोड़ें।",
    traveller: "कौन यात्रा कर रहा है?", travellerSub: "MILGI को बताएं राइड किसके लिए है।", myself: "मैं", someone: "कोई और", group: "परिवार / समूह", destination: "गंतव्य चुनें", destinationSub: "पिकअप और गंतव्य जोड़ें।", pickup: "पिकअप", current: "वर्तमान स्थान लें", destinationLabel: "गंतव्य", searchDestination: "गंतव्य खोजें", continue: "आगे बढ़ें", ride: "अपनी राइड चुनें", rideSub: "अपने लिए सही विकल्प चुनें।", auto: "ऑटो", van: "वैन", bus: "बस", confirmRide: "राइड पक्की करें", fare: "अनुमानित किराया",
    searching: "पार्टनर खोज रहे हैं", searchingSub: "पास में उपलब्ध MILGI पार्टनर खोजा जा रहा है।", found: "पार्टनर मिल गया", arriving: "पार्टनर आ रहा है", arrived: "पार्टनर पहुँच गया", boarding: "बोर्ड करने के लिए तैयार", secured: "राइड सुरक्षित है", live: "आपकी राइड चल रही है", arrivedDest: "आप पहुँच गए", payment: "भुगतान", rating: "आपकी राइड कैसी रही?", next: "आगे", viewLive: "लाइव राइड देखें", pay: "भुगतान पूरा करें", done: "हो गया",
    routesTitle: "नियमित रूट", routesSub: "बार-बार होने वाली यात्राएँ सेव करें।", createRoute: "रूट बनाएँ", myRoutes: "मेरे रूट", subscription: "सब्सक्रिप्शन", routeFrom: "कहाँ से", routeTo: "कहाँ तक", days: "यात्रा के दिन", morningEvening: "सुबह / शाम", plan: "प्लान", saveRoute: "रूट सेव करें",
    institution: "संस्थान परिवहन", institutionSub: "मौजूदा परिवहन को कनेक्ट और मैनेज करें।", school: "स्कूल", university: "यूनिवर्सिटी", company: "कंपनी", hospital: "अस्पताल", institutionName: "संस्थान का नाम", fleet: "फ्लीट", fleetSub: "इस संस्थान से जुड़े मौजूदा वाहन।", busFleet: "बस फ्लीट", vanFleet: "वैन / कार फ्लीट", routeSchedule: "रूट और समय", connect: "परिवहन कनेक्ट करें",
    goodsTitle: "सामान परिवहन", goodsSub: "स्थानीय सामान की यात्रा यहाँ होगी।", goodsPickup: "पिकअप स्थान", goodsDelivery: "डिलीवरी स्थान", vehicleType: "वाहन प्रकार", goodsNotice: "सामान बुकिंग अभी उपलब्ध नहीं है।",
    tripsTitle: "आपकी यात्राएँ", tripsSub: "पिछली और सक्रिय यात्राएँ।", activeTitle: "सक्रिय राइड", activeSub: "आपकी वर्तमान MILGI यात्रा।", noTrips: "अभी कोई यात्रा नहीं।", profileTitle: "प्रोफ़ाइल", profileSub: "आपका MILGI खाता।", personal: "व्यक्तिगत जानकारी", preferences: "पसंद", payments: "भुगतान", helpSafety: "मदद और सुरक्षा", logout: "लॉग आउट", notifications: "सूचनाएँ", rideUpdate: "राइड अपडेट", routeUpdate: "रूट अपडेट", account: "खाता", sos: "सुरक्षा और SOS", emergency: "इमरजेंसी SOS", emergencyContact: "इमरजेंसी संपर्क", support: "MILGI सहायता", help: "मदद केंद्र", faqs: "सामान्य सवाल", contact: "सपोर्ट से संपर्क", safety: "सुरक्षा जानकारी", personalized: "व्यक्तिगत अनुभव",
  },
};

function Icon({ name, size = 20 }) {
  const paths = {
    arrow: <><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></>,
    home: <><path d="m3 10 9-7 9 7"/><path d="M5 9v11h14V9"/><path d="M9 20v-6h6v6"/></>,
    trip: <><circle cx="12" cy="12" r="8"/><path d="M12 8v5l3 2"/></>,
    active: <><circle cx="12" cy="12" r="8"/><path d="M12 8v4l3 2"/></>,
    user: <><circle cx="12" cy="8" r="3"/><path d="M5 20c.8-3.4 3.1-5 7-5s6.2 1.6 7 5"/></>,
    pin: <><path d="M12 21s7-6.2 7-12a7 7 0 0 0-14 0c0 5.8 7 12 7 12Z"/><circle cx="12" cy="9" r="2.3"/></>,
    people: <><circle cx="9" cy="8" r="3"/><circle cx="17" cy="10" r="2.5"/><path d="M3.5 20c.6-4 2.4-6 5.5-6s4.9 2 5.5 6"/><path d="M14 15c3.2-.3 5 1.2 5.6 4"/></>,
    box: <><path d="m4 7 8-4 8 4-8 4-8-4Z"/><path d="M4 7v10l8 4 8-4V7"/><path d="M12 11v10"/></>,
    route: <><circle cx="6" cy="18" r="2"/><circle cx="18" cy="6" r="2"/><path d="M8 18h3a4 4 0 0 0 4-4V10a4 4 0 0 1 4-4"/></>,
    building: <><path d="M4 21V5l8-3 8 3v16"/><path d="M8 8h2M14 8h2M8 12h2M14 12h2M8 16h2M14 16h2"/></>,
    shield: <><path d="M12 3 20 6v6c0 5-3.2 8-8 9-4.8-1-8-4-8-9V6l8-3Z"/><path d="m9 12 2 2 4-4"/></>,
    bell: <><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,
    language: <><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18"/></>,
    location: <><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/></>,
    car: <><path d="m4 14 2-6h12l2 6v5h-2v-3H6v3H4v-5Z"/><path d="M6 14h12M7 11h10"/><circle cx="7" cy="17" r="1"/><circle cx="17" cy="17" r="1"/></>,
    bus: <><rect x="5" y="3" width="14" height="17" rx="3"/><path d="M5 13h14M8 7h3M13 7h3M8 17h.01M16 17h.01"/></>,
    van: <><path d="M3 16V7h11l4 4h3v5"/><path d="M14 7v4h4"/><circle cx="7" cy="17" r="2"/><circle cx="18" cy="17" r="2"/></>,
    star: <><path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3Z"/></>,
    close: <><path d="m6 6 12 12M18 6 6 18"/></>,
    chevron: <path d="m9 6 6 6-6 6"/>,
  };
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name] || paths.arrow}</svg>;
}

function Logo({ theme = "default", large = false }) {
  return <img className={large ? "milgi-logo large" : "milgi-logo"} src={THEMES[theme].logo} alt="MILGI" />;
}

function App() {
  const [token, setToken] = useState(localStorage.getItem("milgi_token"));
  const [userId, setUserId] = useState(localStorage.getItem("milgi_user_id"));
  const [screen, setScreen] = useState(token ? "home" : "splash");
  const [authMode, setAuthMode] = useState("login");
  const [theme, setTheme] = useState(localStorage.getItem("milgi_theme") || "default");
  const [useMode, setUseMode] = useState(localStorage.getItem("milgi_use_mode") || "everyday");
  const [language, setLanguage] = useState(localStorage.getItem("milgi_language") || "en");
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [signupEmail, setSignupEmail] = useState(""); const [signupPassword, setSignupPassword] = useState("");
  const [pickup, setPickup] = useState(""); const [destination, setDestination] = useState(""); const [rideType, setRideType] = useState("Auto"); const [fare, setFare] = useState(80); const [traveller, setTraveller] = useState("myself");
  const [activeRide, setActiveRide] = useState(null); const [rides, setRides] = useState([]); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const [splashDone, setSplashDone] = useState(false); const [demoMode, setDemoMode] = useState(localStorage.getItem("milgi_demo") === "1");
  const [institutionType, setInstitutionType] = useState(""); const [institutionName, setInstitutionName] = useState("");
  const t = useMemo(() => COPY[language], [language]); const colors = THEMES[theme]; const loggedIn = Boolean(token && userId);

  useEffect(() => { if (screen === "splash") { const timer = setTimeout(() => setSplashDone(true), 2200); return () => clearTimeout(timer); } }, [screen]);
  function selectLanguage(value) { setLanguage(value); localStorage.setItem("milgi_language", value); }
  function chooseTheme(value) { setTheme(value); localStorage.setItem("milgi_theme", value); }
  function chooseUseMode(value) { setUseMode(value); localStorage.setItem("milgi_use_mode", value); }
  function saveSession(data) { localStorage.setItem("milgi_token", data.access_token); localStorage.setItem("milgi_user_id", data.user_id); localStorage.removeItem("milgi_demo"); setDemoMode(false); setToken(data.access_token); setUserId(data.user_id); setScreen("home"); }
  function enterPreview() { localStorage.setItem("milgi_demo", "1"); setDemoMode(true); setToken("demo-token"); setUserId("demo-passenger"); setActiveRide(null); setRides([]); setMessage(""); setScreen("home"); }
  function logout() { localStorage.removeItem("milgi_token"); localStorage.removeItem("milgi_user_id"); localStorage.removeItem("milgi_demo"); setDemoMode(false); setToken(null); setUserId(null); setActiveRide(null); setScreen("splash"); }
  async function login(e) { e.preventDefault(); setLoading(true); setMessage(""); try { const { data } = await axios.post(`${API_URL}/auth/login`, { email, password }); if (data.role !== "passenger") throw new Error("This account is not a passenger account."); saveSession(data); setPassword(""); } catch (err) { const offline = !err.response && err.request; setMessage(err.response?.data?.detail || (offline ? (language === "hi" ? "MILGI backend अभी चालू नहीं है। नीचे Preview MILGI से UI देखें।" : "MILGI backend is not running. Use Preview MILGI below to explore the UI.") : err.message) || "Unable to sign in."); } finally { setLoading(false); } }
  async function signup(e) { e.preventDefault(); setLoading(true); setMessage(""); try { await axios.post(`${API_URL}/auth/register`, { full_name: name, phone, email: signupEmail, password: signupPassword, role: "passenger" }); setEmail(signupEmail); setPassword(""); setAuthMode("login"); setMessage(language === "hi" ? "खाता बन गया। अब साइन इन करें।" : "Account created. Please sign in."); } catch (err) { const offline = !err.response && err.request; setMessage(err.response?.data?.detail || (offline ? (language === "hi" ? "Backend अभी उपलब्ध नहीं है। UI देखने के लिए Preview MILGI इस्तेमाल करें।" : "Backend is not available. Use Preview MILGI to explore the UI.") : "Could not create account.")); } finally { setLoading(false); } }
  async function requestRide() { if (!pickup || !destination) { setMessage(language === "hi" ? "पिकअप और गंतव्य जोड़ें।" : "Please add pickup and destination."); return; } if (demoMode) { setActiveRide({ id: "demo-ride", status: "requested", pickup_location: pickup, destination, estimated_fare: Number(fare) }); setScreen("searching"); return; } setLoading(true); setMessage(""); try { const { data } = await axios.post(`${API_URL}/rides/request`, { pickup_location: pickup, destination, estimated_fare: Number(fare) }, { headers: { Authorization: `Bearer ${token}` } }); setActiveRide(data); setScreen("searching"); } catch (err) { if (err.response?.status === 401) logout(); else setMessage(err.response?.data?.detail || "Could not request ride."); } finally { setLoading(false); } }
  async function loadActiveRide() { if (!token || demoMode) return; try { const { data } = await axios.get(`${API_URL}/rides/active/passenger`, { headers: { Authorization: `Bearer ${token}` } }); setActiveRide(data || null); if (data) { if (data.status === "requested") setScreen("searching"); else if (data.status === "accepted") setScreen("found"); else if (data.status === "started") setScreen("live"); else if (data.status === "completed") setScreen("payment"); } } catch (err) { if (err.response?.status === 401) logout(); } }
  async function loadRides() { if (!token || demoMode) return; try { const { data } = await axios.get(`${API_URL}/rides/my`, { headers: { Authorization: `Bearer ${token}` } }); setRides(data || []); } catch (err) { if (err.response?.status === 401) logout(); } }
  useEffect(() => { if (!loggedIn || demoMode) return; loadActiveRide(); const timer = setInterval(loadActiveRide, 2500); return () => clearInterval(timer); }, [token, userId, demoMode]);
  useEffect(() => { if (screen === "trips" && loggedIn) loadRides(); }, [screen, loggedIn]);

  const header = (title, subtitle, back = true) => <div className="screen-header" style={{ background: colors.soft }}><div className="brandline"><Logo theme={theme} /></div><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}{back && <button className="back" onClick={() => setScreen("home")}><Icon name="chevron" size={15} />{t.back}</button>}</div>;
  const shell = (children, cls = "") => <div className={`phone-shell ${cls}`} style={{ "--accent": colors.accent, "--soft": colors.soft, "--warm": colors.warm }}>{children}</div>;

  if (!loggedIn) {
    if (screen === "splash") return shell(<div className="splash"><div className={`splash-logo ${splashDone ? "done" : ""}`}><Logo theme="default" large /><div className="road"><span /></div></div><p className="logo-caption">{t.tagline}</p><p className="splash-copy">People • Goods • Routes • Institutions</p>{splashDone && <div className="splash-actions"><button className="choice yellow" onClick={() => setScreen("language")}>{t.welcome}<Icon name="arrow" /></button><button className="choice outline" onClick={() => setScreen("language")}>{t.move}<Icon name="arrow" /></button></div>}</div>);
    if (screen === "language") return shell(<><div className="intro-top"><Logo theme="default" /><button className="mini-lang"><Icon name="language" size={15} /> {language === "en" ? "EN" : "HI"}</button></div><div className="intro-body"><div className="intro-icon"><Icon name="language" size={28} /></div><h1>{t.chooseLanguage}</h1><p>{t.languageSub}</p><ChoiceCard title="English" text="Continue in English" tone="blue" selected={language === "en"} onClick={() => selectLanguage("en")} /><ChoiceCard title="हिन्दी" text="हिन्दी में जारी रखें" tone="green" selected={language === "hi"} onClick={() => selectLanguage("hi")} /><button className="primary" onClick={() => setScreen("experience")}>{t.continue}<Icon name="arrow" /></button></div></>);
    if (screen === "experience") return shell(<><div className="intro-top"><Logo theme="default" /><button className="text-link" onClick={() => setScreen("language")}>{t.back}</button></div><div className="intro-body"><h1>{t.category}</h1><p>{t.categorySub}</p><ChoiceCard title={t.woman} text="Pink experience theme" tone="pink" onClick={() => { chooseTheme("woman"); setScreen("useMode"); }} /><ChoiceCard title={t.man} text="Blue experience theme" tone="blue" onClick={() => { chooseTheme("man"); setScreen("useMode"); }} /><ChoiceCard title={t.kids} text="Child-friendly experience layer" tone="orange" onClick={() => { chooseTheme("kids"); setScreen("useMode"); }} /><ChoiceCard title={t.senior} text="High-clarity neutral experience" tone="green" onClick={() => { chooseTheme("senior"); setScreen("useMode"); }} /></div></>);
    if (screen === "useMode") return shell(<><div className="intro-top"><Logo theme={theme} /><button className="text-link" onClick={() => setScreen("experience")}>{t.back}</button></div><div className="intro-body"><h1>{t.use}</h1><p>{t.useSub}</p><ChoiceCard title={t.everyday} text={t.everydayDesc} tone="yellow" onClick={() => { chooseUseMode("everyday"); setScreen("auth"); }} /><ChoiceCard title={t.village} text={t.villageDesc} tone="orange" onClick={() => { chooseUseMode("village"); setScreen("auth"); }} /><ChoiceCard title={t.occasional} text={t.occasionalDesc} tone="yellow" onClick={() => { chooseUseMode("occasional"); setScreen("auth"); }} /></div></>);
    return shell(<>{header(authMode === "login" ? t.signIn : t.signUp, authMode === "login" ? t.signInSub : t.signUpSub, false)}<div className="screen-body auth-body"><form onSubmit={authMode === "login" ? login : signup} className="form">{authMode === "signup" && <><label>{t.fullName}</label><input value={name} onChange={e => setName(e.target.value)} required /><label>{t.mobile}</label><input value={phone} onChange={e => setPhone(e.target.value)} required /></>}<label>{t.email}</label><input type="email" value={authMode === "login" ? email : signupEmail} onChange={e => authMode === "login" ? setEmail(e.target.value) : setSignupEmail(e.target.value)} required /><label>{t.password}</label><input type="password" value={authMode === "login" ? password : signupPassword} onChange={e => authMode === "login" ? setPassword(e.target.value) : setSignupPassword(e.target.value)} minLength={6} required /><button className="primary" disabled={loading}>{loading ? t.wait : authMode === "login" ? t.signInBtn : t.create}<Icon name="arrow" /></button></form>{message && <div className="message">{message}</div>}<button className="text-button" onClick={() => { setAuthMode(authMode === "login" ? "signup" : "login"); setMessage(""); }}>{authMode === "login" ? t.newUser : t.existing}</button>{import.meta.env.DEV && <button type="button" className="preview-button" onClick={enterPreview}><span><strong>{t.preview}</strong><small>{t.previewSub}</small></span><Icon name="arrow" /></button>}<div className="language"><button className={language === "en" ? "selected" : ""} onClick={() => selectLanguage("en")}>English</button><button className={language === "hi" ? "selected" : ""} onClick={() => selectLanguage("hi")}>हिन्दी</button></div></div></>);
  }

  const homeCards = [
    { title: t.setDestination, text: t.setDestinationDesc, tone: "yellow", icon: "pin", action: () => setScreen("destination") },
    { title: t.people, text: t.peopleDesc, tone: "pink", icon: "people", action: () => setScreen("traveller") },
    { title: t.goods, text: t.goodsDesc, tone: "blue", icon: "box", badge: t.coming, action: () => setScreen("goods") },
    { title: t.routes, text: t.routesDesc, tone: "yellow", icon: "route", action: () => setScreen("routes") },
    { title: t.institutions, text: t.institutionsDesc, tone: "green", icon: "building", action: () => setScreen("institutions") },
  ];

  return shell(<>
    {screen === "home" && <><div className="home-hero" style={{ background: colors.soft }}><Logo theme={theme} /><div className="hero-copy"><h1>{t.homeTitle}</h1><p>{t.morning}</p></div><button className="bell-btn" onClick={() => setScreen("notifications")}><Icon name="bell" size={19} /></button></div><div className="screen-body"><div className="choose-label">{t.chooseService}</div>{homeCards.map(c => <ChoiceCard key={c.title} {...c} onClick={c.action} />)}<div className="home-note"><Icon name="shield" size={18} /><span>{language === "hi" ? "MILGI आपके लिए स्थानीय परिवहन को एक जगह जोड़ता है।" : "MILGI brings local transport together in one place."}</span></div></div></>}
    {screen === "traveller" && <><>{header(t.traveller, t.travellerSub)}</><div className="screen-body"><ChoiceCard title={t.myself} text={language === "hi" ? "अपने लिए राइड" : "Ride for you"} tone="green" icon="user" selected={traveller === "myself"} onClick={() => setTraveller("myself")} /><ChoiceCard title={t.someone} text={language === "hi" ? "किसी और के लिए राइड" : "Ride for another person"} tone="pink" icon="people" selected={traveller === "someone"} onClick={() => setTraveller("someone")} /><ChoiceCard title={t.group} text={language === "hi" ? "परिवार या समूह" : "Family or group travel"} tone="yellow" icon="people" selected={traveller === "group"} onClick={() => setTraveller("group")} /><button className="primary" onClick={() => setScreen("destination")}>{t.continue}<Icon name="arrow" /></button></div></>}
    {screen === "destination" && <><>{header(t.destination, t.destinationSub)}</><div className="screen-body"><div className="location-banner"><Icon name="location" /><div><strong>{t.current}</strong><span>{language === "hi" ? "आपका वर्तमान स्थान अपने आप लिया जा सकता है" : "Your current location can be used automatically"}</span></div><button onClick={() => setPickup(language === "hi" ? "वर्तमान स्थान" : "Current location")}><Icon name="arrow" size={17} /></button></div><Field title={t.pickup} value={pickup} onChange={setPickup} placeholder={t.current} icon="pin" /><Field title={t.destinationLabel} value={destination} onChange={setDestination} placeholder={t.searchDestination} icon="pin" /><button className="primary" onClick={() => setScreen("rideType")}>{t.continue}<Icon name="arrow" /></button>{message && <div className="message">{message}</div>}</div></>}
    {screen === "rideType" && <><>{header(t.ride, t.rideSub)}</><div className="screen-body"><div className="enter-title">{language === "hi" ? "चुनें…" : "Choose…"}</div><ChoiceCard title={t.auto} text={language === "hi" ? "स्थानीय यात्रा" : "Quick local ride"} tone="pink" icon="car" selected={rideType === "Auto"} onClick={() => { setRideType("Auto"); setFare(80); }} /><ChoiceCard title={t.van} text={language === "hi" ? "परिवार / अधिक सीटें" : "More seats / family travel"} tone="blue" icon="van" selected={rideType === "Van"} onClick={() => { setRideType("Van"); setFare(120); }} /><ChoiceCard title={t.bus} text={language === "hi" ? "समूह / रूट यात्रा" : "Group or route travel"} tone="green" icon="bus" selected={rideType === "Bus"} onClick={() => { setRideType("Bus"); setFare(60); }} /><div className="fare-line"><span>{t.fare}</span><strong>₹{fare}</strong></div><button className="primary" onClick={requestRide} disabled={loading}>{loading ? t.wait : t.confirmRide}<Icon name="arrow" /></button>{message && <div className="message">{message}</div>}</div></>}
    {screen === "searching" && <StatusScreen title={t.searching} subtitle={t.searchingSub} icon="location" cards={[{a: language === "hi" ? "खोज रहे हैं…" : "Searching…", b: language === "hi" ? "पास के पार्टनर और वाहन को मैच किया जा रहा है।" : "Matching nearby partner and vehicle."}, {a: language === "hi" ? "सुरक्षित मैचिंग" : "Safe matching", b: language === "hi" ? "पार्टनर मिलने से पहले आप अनुरोध रद्द कर सकते हैं।" : "You can cancel before a partner accepts."}]} />}
    {screen === "found" && <StatusScreen title={t.found} subtitle={language === "hi" ? "आपकी राइड कन्फर्म है।" : "Your ride is confirmed."} icon="people" cards={[{a:"MILGI Partner",b:language === "hi" ? "सत्यापित पार्टनर • पास में" : "Verified partner • nearby"},{a:"Vehicle",b:`${rideType} • ${language === "hi" ? "आपकी बुकिंग" : "your booking"}`},{a:language === "hi" ? "आने का समय" : "Arrives in",b:"5 min"}]} button={t.next} onNext={() => setScreen("arriving")} />}
    {screen === "arriving" && <StatusScreen title={t.arriving} subtitle={language === "hi" ? "पिकअप तक वाहन को ट्रैक करें।" : "Track the vehicle on the way to you."} icon="location" cards={[{a:language === "hi" ? "लाइव लोकेशन" : "Live location",b:language === "hi" ? "पार्टनर आपकी ओर आ रहा है।" : "Partner is moving toward pickup."},{a:language === "hi" ? "पार्टनर से संपर्क" : "Contact partner",b:language === "hi" ? "कॉल / मैसेज सुरक्षित तरीके से।" : "Call / message safely."}]} button={t.next} onNext={() => setScreen("arrived")} />}
    {screen === "arrived" && <StatusScreen title={t.arrived} subtitle={language === "hi" ? "बोर्ड करने से पहले वाहन की जाँच करें।" : "Check the vehicle before boarding."} icon="car" cards={[{a:language === "hi" ? "वाहन की जाँच" : "Vehicle check",b:language === "hi" ? "बुकिंग में दिख रहे वाहन विवरण से मिलाएँ।" : "Match the vehicle details shown in your booking."},{a:language === "hi" ? "सुरक्षित बोर्डिंग" : "Board safely",b:language === "hi" ? "तैयार होने पर आगे बढ़ें।" : "Continue when you are ready."}]} button={t.next} onNext={() => setScreen("boarding")} />}
    {screen === "boarding" && <StatusScreen title={t.boarding} subtitle={language === "hi" ? "राइड शुरू करने से पहले पुष्टि करें।" : "Confirm the ride before departure."} icon="shield" cards={[{a:language === "hi" ? "राइड कोड" : "Ride code",b:language === "hi" ? "अपना राइड कोड दिखाएँ / पुष्टि करें।" : "Show / confirm your ride code."}]} button={language === "hi" ? "बोर्डिंग पक्की करें" : "Confirm boarding"} onNext={() => setScreen("secured")} />}
    {screen === "secured" && <StatusScreen title={t.secured} subtitle={language === "hi" ? "आपकी यात्रा सुरक्षित रूप से शुरू हो रही है।" : "Your trip is now active."} icon="shield" cards={[{a:language === "hi" ? "ट्रिप सुरक्षित" : "Trip secured",b:language === "hi" ? "यात्री + पार्टनर + वाहन मैच हो गए।" : "Passenger + partner + vehicle matched."},{a:language === "hi" ? "लाइव राइड" : "Live ride",b:language === "hi" ? "रूट और यात्रा स्थिति देखें।" : "Track route and trip status."}]} button={t.viewLive} onNext={() => setScreen("live")} />}
    {screen === "live" && <StatusScreen title={t.live} subtitle={language === "hi" ? "रूट और यात्रा स्थिति ट्रैक करें।" : "Track route and trip status."} icon="route" cards={[{a:language === "hi" ? "लाइव रूट" : "Live route",b:`${pickup || (language === "hi" ? "पिकअप" : "Pickup")} → ${destination || (language === "hi" ? "गंतव्य" : "Destination")}`},{a:"Safety & SOS",b:language === "hi" ? "तुरंत मदद के लिए पहुँच।" : "Quick access to help."},{a:language === "hi" ? "गंतव्य" : "Destination",b:language === "hi" ? "ETA यहाँ दिखेगा।" : "ETA shown here."}]} button={t.next} onNext={() => setScreen("arrivedDest")} />}
    {screen === "arrivedDest" && <StatusScreen title={t.arrivedDest} subtitle={language === "hi" ? "ट्रिप सुरक्षित रूप से पूरी हुई।" : "Trip completed safely."} icon="pin" cards={[{a:language === "hi" ? "ट्रिप पूरी" : "Trip complete",b:language === "hi" ? "अब भुगतान विवरण देखें।" : "Review payment details."}]} button={language === "hi" ? "भुगतान पर जाएँ" : "Continue to payment"} onNext={() => setScreen("payment")} />}
    {screen === "payment" && <StatusScreen title={t.payment} subtitle={language === "hi" ? "अपना किराया देखें।" : "Review your ride fare."} icon="box" cards={[{a:language === "hi" ? "राइड किराया" : "Ride fare",b:`₹${activeRide?.estimated_fare || fare}`},{a:language === "hi" ? "भुगतान तरीका" : "Payment method",b:"UPI / Card / Cash"}]} button={t.pay} onNext={() => setScreen("rating")} />}
    {screen === "rating" && <StatusScreen title={t.rating} subtitle={language === "hi" ? "आपका फीडबैक MILGI को बेहतर बनाता है।" : "Your feedback helps MILGI improve."} icon="star" cards={[{a:language === "hi" ? "पार्टनर को रेट करें" : "Rate partner",b:"☆ ☆ ☆ ☆ ☆"},{a:language === "hi" ? "फीडबैक" : "Feedback",b:language === "hi" ? "अपने अनुभव के बारे में बताएँ।" : "Tell us about your experience."}]} button={t.done} onNext={() => { setScreen("home"); loadRides(); }} />}
    {screen === "routes" && <><>{header(t.routesTitle, t.routesSub)}</><div className="screen-body"><ChoiceCard title={t.createRoute} text={`${t.morningEvening} / ${language === "hi" ? "साप्ताहिक / मासिक" : "weekly / monthly"}`} tone="yellow" icon="route" onClick={() => setScreen("createRoute")} /><ChoiceCard title={t.myRoutes} text={language === "hi" ? "सेव किए गए रूट मैनेज करें।" : "Manage your saved recurring routes."} tone="green" icon="trip" /><ChoiceCard title={t.subscription} text={language === "hi" ? "बार-बार की यात्रा के लिए प्लान।" : "Plan for recurring travel."} tone="yellow" icon="star" /></div></>}
    {screen === "createRoute" && <><>{header(t.createRoute, t.routesSub)}</><div className="screen-body"><Field title={t.routeFrom} value={pickup} onChange={setPickup} placeholder={language === "hi" ? "घर" : "Home"} icon="pin" /><Field title={t.routeTo} value={destination} onChange={setDestination} placeholder={language === "hi" ? "काम / स्कूल / कॉलेज" : "Work / School / College"} icon="pin" /><div className="section-label">{t.days}</div><div className="day-grid">{["Mon","Tue","Wed","Thu","Fri","Sat"].map(d => <button key={d} className="day-chip selected">{language === "hi" ? {Mon:"सोम",Tue:"मंगल",Wed:"बुध",Thu:"गुरु",Fri:"शुक्र",Sat:"शनि"}[d] : d}</button>)}</div><ChoiceCard title={t.morningEvening} text={language === "hi" ? "सुबह / शाम की नियमित यात्रा" : "Regular morning or evening travel"} tone="yellow" icon="active" /><ChoiceCard title={t.plan} text={language === "hi" ? "साप्ताहिक या मासिक" : "Weekly or monthly"} tone="green" icon="star" /><button className="primary" onClick={() => setScreen("routes")}>{t.saveRoute}<Icon name="arrow" /></button></div></>}
    {screen === "institutions" && <><>{header(t.institution, t.institutionSub)}</><div className="screen-body"><div className="section-label">{language === "hi" ? "संस्थान चुनें" : "Choose institution"}</div>{[["school",t.school],["university",t.university],["company",t.company],["hospital",t.hospital]].map(([id,label],i) => <ChoiceCard key={id} title={label} text={language === "hi" ? "मौजूदा परिवहन से कनेक्ट करें" : "Connect existing transport"} tone={i===1?"blue":i===2?"yellow":"green"} icon="building" selected={institutionType===id} onClick={() => {setInstitutionType(id); setScreen("institutionDetails");}} />)}</div></>}
    {screen === "institutionDetails" && <><>{header(t.institutionName, t.institutionSub)}</><div className="screen-body"><Field title={t.institutionName} value={institutionName} onChange={setInstitutionName} placeholder={language === "hi" ? "नाम लिखें" : "Enter institution name"} icon="building" /><ChoiceCard title={t.fleet} text={t.fleetSub} tone="blue" icon="bus" onClick={() => setScreen("fleet")} /><ChoiceCard title={t.routeSchedule} text={language === "hi" ? "स्टॉप और समय देखें" : "Stops and schedules"} tone="green" icon="route" onClick={() => setScreen("institutionRoute")} /><button className="primary" onClick={() => setScreen("fleet")}>{t.continue}<Icon name="arrow" /></button></div></>}
    {screen === "fleet" && <><>{header(t.fleet, t.fleetSub)}</><div className="screen-body"><ChoiceCard title={t.busFleet} text={language === "hi" ? "स्कूल / समूह परिवहन" : "School / group transport"} tone="green" icon="bus" /><ChoiceCard title={t.vanFleet} text={language === "hi" ? "छोटी फ्लीट / स्टाफ परिवहन" : "Smaller fleet / staff transport"} tone="blue" icon="van" /><ChoiceCard title={language === "hi" ? "कनेक्टेड वाहन" : "Connected vehicles"} text={language === "hi" ? "MILGI से जुड़े मौजूदा वाहन" : "Existing vehicles connected to MILGI"} tone="yellow" icon="car" /><button className="primary" onClick={() => setScreen("institutionRoute")}>{t.routeSchedule}<Icon name="arrow" /></button></div></>}
    {screen === "institutionRoute" && <><>{header(t.routeSchedule, t.institutionSub)}</><div className="screen-body"><ChoiceCard title={language === "hi" ? "रूट 01" : "Route 01"} text={`${pickup || (language === "hi" ? "मुख्य गेट" : "Main gate")} → ${destination || (language === "hi" ? "कैंपस" : "Campus")}`} tone="green" icon="route" /><ChoiceCard title={language === "hi" ? "सुबह की शिफ्ट" : "Morning schedule"} text={language === "hi" ? "7:30 AM • सोमवार–शुक्रवार" : "7:30 AM • Monday–Friday"} tone="yellow" icon="active" /><button className="primary" onClick={() => setScreen("institutions")}>{t.connect}<Icon name="arrow" /></button></div></>}
    {screen === "goods" && <><>{header(t.goodsTitle, t.goodsSub)}</><div className="screen-body"><div className="coming-card"><div className="coming-icon"><Icon name="box" size={28} /></div><h2>{t.coming}</h2><p>{t.goodsNotice}</p></div><Field title={t.goodsPickup} value="" onChange={() => {}} placeholder={language === "hi" ? "कहाँ से सामान लेना है?" : "Where should goods be collected?"} icon="pin" /><Field title={t.goodsDelivery} value="" onChange={() => {}} placeholder={language === "hi" ? "कहाँ पहुँचाना है?" : "Where should goods go?"} icon="pin" /><ChoiceCard title={t.vehicleType} text={language === "hi" ? "टेम्पो / गुड्स वाहन / अन्य" : "Tempo / goods vehicle / other"} tone="blue" icon="van" disabled /><button className="primary disabled-button" disabled>{t.coming}</button></div></>}
    {screen === "trips" && <><>{header(t.tripsTitle, t.tripsSub)}</><div className="screen-body">{rides.length ? rides.map(r => <div className="history-card" key={r.id || r.ride_id}><Icon name="trip" size={18} /><div><strong>{r.status}</strong><span>{r.pickup_location} → {r.drop_location || r.destination}</span></div><b>₹{r.final_fare || r.estimated_fare || 0}</b></div>) : <div className="empty"><Icon name="trip" size={28} /><span>{t.noTrips}</span></div>}</div></>}
    {screen === "active" && <><>{header(t.activeTitle, t.activeSub)}</><div className="screen-body">{activeRide ? <><div className="active-map"><Icon name="route" size={42} /><span>{language === "hi" ? "आपकी लाइव यात्रा" : "Your live journey"}</span></div><Info title={language === "hi" ? "स्थिति" : "Status"} text={activeRide.status} /><Info title={t.pickup} text={activeRide.pickup_location} /><Info title={t.destinationLabel} text={activeRide.drop_location || activeRide.destination} /></> : <div className="empty">{language === "hi" ? "कोई सक्रिय राइड नहीं।" : "No active ride."}</div>}</div></>}
    {screen === "profile" && <><>{header(t.profileTitle, t.profileSub)}</><div className="screen-body"><ChoiceCard title={t.personal} text={language === "hi" ? "नाम, फोन, भाषा" : "Name, phone, language"} tone="green" icon="user" /><ChoiceCard title={t.preferences} text={language === "hi" ? "थीम, अनुभव, सेव की जगहें" : "Theme, experience, saved places"} tone="blue" icon="star" /><ChoiceCard title={t.payments} text={language === "hi" ? "भुगतान के तरीके" : "Payment methods"} tone="yellow" icon="box" /><ChoiceCard title={t.helpSafety} text={language === "hi" ? "SOS, सहायता और FAQ" : "SOS, support and FAQs"} tone="pink" icon="shield" onClick={() => setScreen("help")} /><ChoiceCard title={t.notifications} text={language === "hi" ? "राइड और अकाउंट अपडेट" : "Ride and account updates"} tone="blue" icon="bell" onClick={() => setScreen("notifications")} /><button className="secondary" onClick={logout}>{t.logout}</button></div></>}
    {screen === "notifications" && <><>{header(t.notifications, language === "hi" ? "महत्वपूर्ण राइड और अकाउंट अपडेट।" : "Important ride and account updates.")}</><div className="screen-body"><ChoiceCard title={t.rideUpdate} text={language === "hi" ? "पार्टनर आने और ट्रिप स्थिति।" : "Partner arrival and trip status."} tone="blue" icon="bell" /><ChoiceCard title={t.routeUpdate} text={language === "hi" ? "नियमित रूट रिमाइंडर।" : "Recurring route reminders."} tone="yellow" icon="route" /><ChoiceCard title={t.account} text={language === "hi" ? "सुरक्षा और प्रोफ़ाइल अपडेट।" : "Security and profile updates."} tone="green" icon="user" /></div></>}
    {screen === "sos" && <><>{header(t.sos, language === "hi" ? "मदद हमेशा आसान पहुँच में।" : "Help is always easy to reach.")}</><div className="screen-body"><div className="sos-card"><Icon name="shield" size={30} /><h2>{t.emergency}</h2><p>{language === "hi" ? "तुरंत इमरजेंसी सहायता का अनुरोध करें।" : "Quickly request emergency assistance."}</p><button>{language === "hi" ? "SOS सहायता" : "Request SOS"}</button></div><ChoiceCard title={t.emergencyContact} text={language === "hi" ? "सेव किए गए संपर्क को कॉल करें।" : "Call your saved contact."} tone="pink" icon="people" /><ChoiceCard title={t.support} text={language === "hi" ? "ट्रिप के लिए MILGI सपोर्ट।" : "Contact MILGI support for the trip."} tone="pink" icon="bell" /></div></>}
    {screen === "help" && <><>{header(t.help, language === "hi" ? "जवाब और सहायता पाएं।" : "Find answers and contact support.")}</><div className="screen-body"><ChoiceCard title={t.faqs} text={language === "hi" ? "आम सवाल और मार्गदर्शन।" : "Common questions and guidance."} tone="green" icon="box" /><ChoiceCard title={t.contact} text={language === "hi" ? "ट्रिप या अकाउंट में मदद।" : "Get help with a trip or account."} tone="blue" icon="bell" /><ChoiceCard title={t.safety} text={language === "hi" ? "राइड और अकाउंट सुरक्षा।" : "Ride and account safety."} tone="pink" icon="shield" /><ChoiceCard title={t.personalized} text={language === "hi" ? "आपकी थीम और अनुभव सेटिंग।" : "Your theme and experience settings."} tone="yellow" icon="star" /></div></>}
    {screen === "personalized" && <><>{header(t.personalized, language === "hi" ? "अपना MILGI अनुभव चुनें।" : "Choose your MILGI experience.")}</><div className="screen-body"><ChoiceCard title={t.woman} text="Pink" tone="pink" icon="user" onClick={() => chooseTheme("woman")} /><ChoiceCard title={t.man} text="Blue" tone="blue" icon="user" onClick={() => chooseTheme("man")} /><ChoiceCard title={t.kids} text="Orange" tone="orange" icon="people" onClick={() => chooseTheme("kids")} /><ChoiceCard title={t.senior} text="Light" tone="green" icon="user" onClick={() => chooseTheme("senior")} /></div></>}
    <nav className="bottom-nav"><button className={screen === "home" ? "active" : ""} onClick={() => setScreen("home")}><Icon name="home" />{t.home}</button><button className={screen === "trips" ? "active" : ""} onClick={() => setScreen("trips")}><Icon name="trip" />{t.trips}</button><button className={screen === "active" ? "active" : ""} onClick={() => { loadActiveRide(); setScreen("active"); }}><Icon name="active" />{t.active}</button><button className={screen === "profile" ? "active" : ""} onClick={() => setScreen("profile")}><Icon name="user" />{t.profile}</button></nav>
  </>);
}

function ChoiceCard({ title, text, tone = "green", onClick, disabled, selected, badge, icon }) { return <button className={`choice-card ${tone} ${selected ? "selected-card" : ""} ${disabled ? "disabled-card" : ""}`} onClick={disabled ? undefined : onClick} disabled={disabled}><div className="card-icon">{icon ? <Icon name={icon} size={19} /> : <Icon name="arrow" size={18} />}</div><div className="card-copy"><strong>{title}</strong><span>{text}</span>{badge && <em>{badge}</em>}</div><Icon name="arrow" size={18} /></button>; }
function Field({ title, value, onChange, placeholder, icon = "pin" }) { return <label className="field"><span className="field-title"><Icon name={icon} size={15} />{title}</span><div className="field-control"><input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} /><Icon name="chevron" size={16} /></div></label>; }
function StatusScreen({ title, subtitle, cards, button, onNext, icon = "location" }) { return <><div className="screen-header" style={{ background: "var(--soft)" }}><div className="brandline"><Logo theme="default" /></div><div className="status-title-row"><div className="status-icon"><Icon name={icon} size={22} /></div><div><h1>{title}</h1><p>{subtitle}</p></div></div></div><div className="screen-body">{cards.map((c,i)=><div className={`info-card ${i===0?"strong-card":""}`} key={`${c.a}-${i}`}><strong>{c.a}</strong><span>{c.b}</span></div>)}{button && <button className="primary bottom-action" onClick={onNext}>{button}<Icon name="arrow" /></button>}</div></>; }
function Info({title,text}) { return <div className="info-card"><strong>{title}</strong><span>{text}</span></div>; }

export default App;
